[package]
name = "crawler"
version = "0.1.0"
authors = ["Joël Billard <bibi0401@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.5.4"
reqwest = "0.11.4"
tokio = { version = "1.11.0", features = ["full"] }
async-trait = "0.1.51"
isahc = "1.5.0"
futures = "0.3.17"